### ISSUE TITLE
! LaTeX Error: File `xelatexemoji.sty' not found.

### ISSUE THREAD

**Issue by msubirana** [yihui/latex-pass#32]
Hi, 

I am trying to use emojis in my pdf R markdown output. After a while I saw a that a possible solucion is using the xelatexemoji. I installed but I got this error:

```
! LaTeX Error: File `xelatexemoji.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile report16s.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See report16s.log for more info.
Execution halted
```
I added this code in my r markdown as well

```
header-includes:
   - \usepackage{xelatexemoji}
```

I tried

tlmgr_search('/xelatexemoji.sty') 

And I got: tlmgr: package repository https://ctan.javinator9889.com/systems/texlive/tlnet (verified)

I tried then:
tlmgr_install('https://ctan.javinator9889.com/systems/texlive/tlnet')

and

tlmgr_install('tlnet')

But I didn't work. Any suggestions?

**Comment by cderv** [comment]
Which package the `xelatexemoji` is from ? 

> tlmgr_search('/xelatexemoji.sty')

`tlmgr_search('/xelatexemoji.sty')` return nothing, so it seems it is not part of a package in CTAN. 

> I tried then:
> tlmgr_install('ctan.javinator9889.com/systems/texlive/tlnet')

`tlmgr_install` is for installing package, you need to pass package name not url. 

> tlmgr_install('tlnet')

tlnet is not a package, it is a subfolder of the CTAN url. 

> I am trying to use emojis in my pdf R markdown output.

For emoji in LaTeX, you have other package like `emoji` that would work using LuaLaTeX

````markdown
---
title: "Test"
output: 
  pdf_document:
    latex_engine: lualatex
    extra_dependencies: emoji
---

See a \emoji{joy}

````

There is probably other packages too. But `xelatexemoji`, I can't find it.
