### ISSUE TITLE
Manim Support - Comment

### ISSUE THREAD

**Issue by naveen521kk** [yihui/latex-pass#8]
I would like to help some of the Manim Users for latex related issues. (missing packages)
Can you add a comment of what to do if they have installed [manim-latex](https://chocolatey.org/packages/manim-latex) in the comment the bot posts as in https://github.com/yihui/latex-pass/pull/1#issuecomment-700045084 ?
Just editing the last line `If you use TinyTeX but are not an R user, you may install these packages via command line:` would help a lot.
Thank You.

**Comment by yihui** [comment]
Yes, I'll be happy to add a comment. Just tell me how you want me to add it, or add it by yourself in a PR---the comment comes from the script here: https://github.com/yihui/latex-pass/blob/ad2c32b7ab746705e7c47616628eb14fd6a4c51e/latex-pass.R#L20
